### ISSUE TITLE
I cant get it run ?

### ISSUE THREAD

**Issue by AMoktar** [ddtraceweb/smtp-validator-email#25]
sorry for this 
I downloaded the latest version clone
I cant get it run 
I have a localserver and online server but i donot know where to start ?!

**Comment by ddtraceweb** [comment]
you must have smtp active and configure in your php.ini and server.

**Comment by AMoktar** [comment]
Thanks for respond
my server is set smtp is active
I don't know how to create a test.php or example.php
I'm not sure what to require in my test.php file ?

**Comment by rubenCodeforges** [comment]
@AMoktar  what do you want to do with this library ?

**Comment by warunasanjayanew** [comment]
How to check whether email is valid? Only ting i am getting is?array(1) { ["warunasanjayanjkjkjkew@yahoo.com"]=> array(2) { ["result"]=> int(0) ["info"]=> string(18) "catch all detected" } }. I am not seeing any boolean.

**Comment by rubenCodeforges** [comment]
@warunasanjayanew  ahh  you already have the result
```
["result"]=>0  //Validation failed 
["info"] => "catch all detected"  //And this is the reason why it failed
```

**Comment by rubenCodeforges** [comment]
@warunasanjayanew in php 0/1 is a boolean 
meaning 0 = false 1 = true

**Comment by rubenCodeforges** [comment]
@ddtraceweb seems to be solved , you can close it

**Comment by warunasanjayanew** [comment]
No . Your program return 0 for valid mails too.
Here is the code I wrote.
<?php
use SmtpValidatorEmail\ValidatorEmail;
ini_set('max_execution_time', 300);//300 seconds
$from = 'xyz@xzzz.com'; 
$email = 'waruna0sanjaya@gmail.com';
$options = array('domainMoreInfo' => true,'catchAllIsValid' => 0);
$validator = new ValidatorEmail(array($email), $from,$options);
$array=$validator->getResults();
print_r(strval($array[$email]['info']));
print_r(strval($array[$email]['result']));
Here is the result.
catch all detected0

**Comment by rubenCodeforges** [comment]
@warunasanjayanew  you see catch all has been detected , you can set in setting that catchall detected will be handeled as valid ( 1 ) or as invalid

```

Avaialable default options
array(
  'domainMoreInfo' => false,
  'delaySleep' => array(0),
  'noCommIsValid' => 0,
  'catchAllIsValid' => 0,
  'catchAllEnabled' => 1,
);
```
`    'catchAllIsValid' => 0,` this is by default which means that if catchall was detected validation will fail you can change to 1  and you will get validation true(1) even with catchall

**Comment by rubenCodeforges** [comment]
i think what confuse you is that catchAllIsValid is set by default to false , just switch it to 
  'catchAllIsValid' => 1,

and those emails where a catchalll is detected will be valid but this is bad as you can use any email for that domain.
like $email = 'waruna2220sa2222nja2222ya@gmail.com'; would also be valid even if it doesnt exist but the server has catchall enabled

**Comment by rubenCodeforges** [comment]
@ddtraceweb  please close this one seems to be solved
